name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify your Python version

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        

    - name: Install AWS Elastic Beanstalk CLI
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip
        pip3 install awsebcli --upgrade --user
        export PATH=$PATH:$HOME/.local/bin
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: eu-west-1
    
    - name: Build Docker Image
      run: docker build -t churn-app-mehul .

    - name: Check path
      run: docker run churn-app-mehul ls -R /app
      
    - name: Run Tests in Docker
      run: docker run churn-app-mehul pytest -v

    - name: Initialize Elastic Beanstalk Application
      run: eb init -p docker churn-app-mehul --region eu-west-1

    - name: Deploy to Elastic Beanstalk
      run: eb deploy Churn-app-mehul-env
